<a href="https://colab.research.google.com/github/pradhansumitXD/AI-ML/blob/main/AI%26ML_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4. TO - DO - Task Please complete all the problem listed below.



# 4.1 Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [4]:
import numpy as np

def length_conversion(amount, source_unit, target_unit):
    if source_unit == 'm' and target_unit == 'ft':
        return np.multiply(amount, 3.28084)
    elif source_unit == 'ft' and target_unit == 'm':
        return np.divide(amount, 3.28084)
    else:
        raise ValueError("Invalid units for length conversion")

def weight_conversion(amount, source_unit, target_unit):
    if source_unit == 'kg' and target_unit == 'lbs':
        return np.multiply(amount, 2.20462)
    elif source_unit == 'lbs' and target_unit == 'kg':
        return np.divide(amount, 2.20462)
    else:
        raise ValueError("Invalid units for weight conversion")

def volume_conversion(amount, source_unit, target_unit):
    if source_unit == 'L' and target_unit == 'gal':
        return np.multiply(amount, 0.264172)
    elif source_unit == 'gal' and target_unit == 'L':
        return np.divide(amount, 0.264172)
    else:
        raise ValueError("Invalid units for volume conversion")

def main():
    print("Welcome to the unit conversion program!")
    conversion_category = input("Choose conversion type (length, weight, volume): ").strip().lower()

    if conversion_category not in ['length', 'weight', 'volume']:
        print("Error: Invalid conversion category selected!")
        return

    try:
        input_value = float(input("Enter the value to be converted: "))

        if conversion_category == 'length':
            input_unit = input("Enter the unit to convert from (m for meters, ft for feet): ").strip()
            output_unit = input("Enter the unit to convert to (m for meters, ft for feet): ").strip()
            result = length_conversion(input_value, input_unit, output_unit)

        elif conversion_category == 'weight':
            input_unit = input("Enter the unit to convert from (kg for kilograms, lbs for pounds): ").strip()
            output_unit = input("Enter the unit to convert to (kg for kilograms, lbs for pounds): ").strip()
            result = weight_conversion(input_value, input_unit, output_unit)

        elif conversion_category == 'volume':
            input_unit = input("Enter the unit to convert from (L for liters, gal for gallons): ").strip()
            output_unit = input("Enter the unit to convert to (L for liters, gal for gallons): ").strip()
            result = volume_conversion(input_value, input_unit, output_unit)

        print(f"The converted value is: {result}")

    except ValueError as e:
        print(f"Error: {e}. Please ensure you enter a valid numeric value and unit combination.")

if __name__ == "__main__":
    main()


Welcome to the unit conversion program!
Choose conversion type (length, weight, volume): volume
Enter the value to be converted: 25
Enter the unit to convert from (L for liters, gal for gallons): L
Enter the unit to convert to (L for liters, gal for gallons): gal
The converted value is: 6.6043


# Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).


3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [5]:
def calculate_sum(values):
    """
    Function to calculate the sum of the numbers in the list.

    Parameters:
    values (list): The list of numbers to be summed.

    Returns:
    float: The sum of the numbers.
    """
    return sum(values)

def calculate_average(values):
    """
    Function to calculate the average of the numbers in the list.

    Parameters:
    values (list): The list of numbers to calculate the average of.

    Returns:
    float: The average of the numbers.
    """
    if len(values) == 0:
        raise ValueError("Cannot calculate the average of an empty list")
    return sum(values) / len(values)

def find_maximum(values):
    """
    Function to find the maximum value in the list.

    Parameters:
    values (list): The list of numbers.

    Returns:
    float: The maximum value in the list.
    """
    if len(values) == 0:
        raise ValueError("Cannot find maximum of an empty list")
    return max(values)

def find_minimum(values):
    """
    Function to find the minimum value in the list.

    Parameters:
    values (list): The list of numbers.

    Returns:
    float: The minimum value in the list.
    """
    if len(values) == 0:
        raise ValueError("Cannot find minimum of an empty list")
    return min(values)

def main():
    print("Welcome to the mathematical operations program!")

    try:
        # Get the list of numbers from the user
        values = input("Please enter a list of numbers separated by spaces: ").strip().split()

        # Convert the input into a list of floats
        values = [float(num) for num in values]

        # Ask the user to choose an operation
        operation = input("Choose an operation (sum, average, maximum, minimum): ").strip().lower()

        # Perform the selected operation
        if operation == 'sum':
            result = calculate_sum(values)
            print(f"The sum of the numbers is: {result}")
        elif operation == 'average':
            result = calculate_average(values)
            print(f"The average of the numbers is: {result}")
        elif operation == 'maximum':
            result = find_maximum(values)
            print(f"The maximum value in the list is: {result}")
        elif operation == 'minimum':
            result = find_minimum(values)
            print(f"The minimum value in the list is: {result}")
        else:
            print("Invalid operation selected.")
    except ValueError as e:
        print(f"Error: {e}. Please make sure to enter valid numbers.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Welcome to the mathematical operations program!
Please enter a list of numbers separated by spaces: 5 4 6 8  9 4 1 5 9
Choose an operation (sum, average, maximum, minimum): sum
The sum of the numbers is: 51.0


# 10. To - Do - NumPy
Please complete all the problems listed below:

# 10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [6]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_matrix = np.empty((2, 2))

# 2. Initialize an all one array with size 4x2
ones_matrix = np.ones((4, 2))

# 3. Return a new array of given shape and type, filled with fill value
filled_matrix = np.full((3, 3), 7)

# 4. Return a new array of zeros with same shape and type as a given array
reference_matrix = np.array([[1, 2], [3, 4]])
zeros_matrix = np.zeros_like(reference_matrix)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_matrix = np.ones_like(reference_matrix)

# 6. Convert the existing list number_list = [1, 2, 3, 4] to a numpy array
number_list = [1, 2, 3, 4]
numpy_array = np.array(number_list)

# Output the results
print('empty_matrix')
print(empty_matrix)

print("ones_matrix")
print(ones_matrix)

print("filled_matrix")
print(filled_matrix)

print("zeros_matrix")
print(zeros_matrix)

print("ones_like_matrix")
print(ones_like_matrix)

print("numpy_array")
print(numpy_array)


empty_matrix
[[1.90503393e-316 0.00000000e+000]
 [0.00000000e+000 7.68799911e-143]]
ones_matrix
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
filled_matrix
[[7 7 7]
 [7 7 7]
 [7 7 7]]
zeros_matrix
[[0 0]
 [0 0]]
ones_like_matrix
[[1 1]
 [1 1]]
numpy_array
[1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [7]:
import numpy as np

# 1. Array with values ranging from 10 to 49
range_array = np.arange(10, 50)

# 2. 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)

# 3. 3x3 identity matrix
identity_matrix = np.eye(3)

# 4. Random array of size 30 and find the mean of the array
random_values = np.random.random(30)
mean_random_values = random_values.mean()

# 5. 10x10 array with random values and find the minimum and maximum values
random_matrix_10x10 = np.random.random((10, 10))
min_random_value = random_matrix_10x10.min()
max_random_value = random_matrix_10x10.max()

# 6. Zero array of size 10 and replace 5th element with 1
modified_zero_array = np.zeros(10)
modified_zero_array[4] = 1  # 5th element is index 4

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
original_array = np.array([1, 2, 0, 0, 4, 0])
reversed_original_array = original_array[::-1]

# 8. 2D array with 1 on the border and 0 inside
border_matrix = np.ones((5, 5))
border_matrix[1:-1, 1:-1] = 0

# 9. 8x8 matrix and fill it with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8))
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1

# Output the results
print("Array with values from 10 to 49:")
print(range_array)
print("\n3x3 Matrix with values from 0 to 8:")
print(matrix_3x3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)
print("\nMean of random array of size 30:")
print(mean_random_values)
print("\n10x10 Array with random values:")
print(random_matrix_10x10)
print("Minimum value :", min_random_value, "\nMaximum value:", max_random_value)
print("\nZero array with 5th element replaced by 1:")
print(modified_zero_array)
print("\nReversed array:")
print(reversed_original_array)
print("\n2D Array with border 1 and inside 0:")
print(border_matrix)
print("\n8x8 Checkerboard pattern:")
print(checkerboard_matrix)


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of random array of size 30:
0.5003850862645154

10x10 Array with random values:
[[0.61467814 0.37372082 0.22285799 0.4204034  0.36028478 0.67189826
  0.82192652 0.15967822 0.53618668 0.22722576]
 [0.4413672  0.48965537 0.64477861 0.87482119 0.48029636 0.55632812
  0.18548831 0.47832563 0.12623076 0.22469111]
 [0.53253234 0.27268624 0.28069455 0.50730618 0.4058761  0.51987506
  0.25448401 0.40555114 0.33772729 0.2607675 ]
 [0.61830165 0.81218479 0.28133255 0.95769839 0.88866088 0.60618043
  0.70915878 0.17130257 0.26259576 0.19161439]
 [0.67688351 0.1524422  0.02857086 0.96267845 0.88818643 0.09604848
  0.35912248 0.83241078 0.25728024 0.32598692]
 [0.34053301 0.27377134 0.70328785 0.4350757  0.76958277 0.

# Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [8]:
import numpy as np

# Given arrays
matrix_x = np.array([[1, 2], [3, 5]])
matrix_y = np.array([[5, 6], [7, 8]])
vector_v = np.array([9, 10])
vector_w = np.array([11, 12])

# 1. Add the two arrays
sum_result = matrix_x + matrix_y

# 2. Subtract the two arrays
difference_result = matrix_x - matrix_y

# 3. Multiply the array with any integers of your choice
scaled_matrix_x = matrix_x * 2  # Example: multiplying matrix_x by 2
scaled_matrix_y = matrix_y * 3  # Example: multiplying matrix_y by 3

# 4. Find the square of each element of the array
squared_matrix_x = np.square(matrix_x)
squared_matrix_y = np.square(matrix_y)

# 5. Find the dot product between: vector_v and vector_w; matrix_x and vector_v; matrix_x and matrix_y
dot_product_vw = np.dot(vector_v, vector_w)
dot_product_xv = np.dot(matrix_x, vector_v)
dot_product_xy = np.dot(matrix_x, matrix_y)

# 6. Concatenate matrix_x and matrix_y along rows and concatenate vector_v and vector_w along columns
concatenated_xy_rows = np.concatenate((matrix_x, matrix_y), axis=0)  # Concatenate along rows
concatenated_vw_columns = np.concatenate((vector_v.reshape(-1, 1), vector_w.reshape(-1, 1)), axis=1)  # Concatenate along columns

# 7. Concatenate matrix_x and vector_v; if an error occurs, observe and explain why
try:
    concatenated_xv = np.concatenate((matrix_x, vector_v), axis=0)  # Attempt to concatenate matrix_x and vector_v along rows
except Exception as e:
    concatenated_xv_error = str(e)

# Output the results
print("Addition of matrix_x and matrix_y:")
print(sum_result)
print("\nSubtraction of matrix_x and matrix_y:")
print(difference_result)
print("\nMultiplying matrix_x by 2 and matrix_y by 3:")
print(scaled_matrix_x)
print(scaled_matrix_y)
print("\nSquare of elements in matrix_x:")
print(squared_matrix_x)
print("\nSquare of elements in matrix_y:")
print(squared_matrix_y)
print("\nDot product of vector_v and vector_w:")
print(dot_product_vw)
print("\nDot product of matrix_x and vector_v:")
print(dot_product_xv)
print("\nDot product of matrix_x and matrix_y:")
print(dot_product_xy)
print("\nConcatenate matrix_x and matrix_y along rows:")
print(concatenated_xy_rows)
print("\nConcatenate vector_v and vector_w along columns:")
print(concatenated_vw_columns)
print("\nConcatenating matrix_x and vector_v:")
print(concatenated_xv_error)


Addition of matrix_x and matrix_y:
[[ 6  8]
 [10 13]]

Subtraction of matrix_x and matrix_y:
[[-4 -4]
 [-4 -3]]

Multiplying matrix_x by 2 and matrix_y by 3:
[[ 2  4]
 [ 6 10]]
[[15 18]
 [21 24]]

Square of elements in matrix_x:
[[ 1  4]
 [ 9 25]]

Square of elements in matrix_y:
[[25 36]
 [49 64]]

Dot product of vector_v and vector_w:
219

Dot product of matrix_x and vector_v:
[29 77]

Dot product of matrix_x and matrix_y:
[[19 22]
 [50 58]]

Concatenate matrix_x and matrix_y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate vector_v and vector_w along columns:
[[ 9 11]
 [10 12]]

Concatenating matrix_x and vector_v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]])   and    B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [9]:
import numpy as np

# Given matrices
matrix_A = np.array([[3, 4], [7, 8]])
matrix_B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
inverse_A = np.linalg.inv(matrix_A)
identity_matrix = np.dot(matrix_A, inverse_A)
print("A * A^-1 (should be identity matrix):")
print(identity_matrix)

# 2. Prove AB != BA
product_AB = np.dot(matrix_A, matrix_B)  # AB
product_BA = np.dot(matrix_B, matrix_A)  # BA
print("\nAB:")
print(product_AB)
print("\nBA:")
print(product_BA)
print("\nIs AB equal to BA?", np.array_equal(product_AB, product_BA))  # Checking if AB == BA

# 3. Prove (AB)^T = B^T * A^T
transpose_AB = np.transpose(product_AB)  # (AB)^T
transpose_BA = np.dot(np.transpose(matrix_B), np.transpose(matrix_A))  # B^T * A^T
print("\n(AB)^T:")
print(transpose_AB)
print("\nB^T * A^T:")
print(transpose_BA)
print("\nIs (AB)^T equal to B^T * A^T?", np.array_equal(transpose_AB, transpose_BA))

# Solve the system of linear equations using inverse method:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system in matrix form: AX = B
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
const_matrix = np.array([-1, -3, 9])

# Use the inverse of coeff_matrix to solve for variables (X = [x, y, z])
inverse_coeff_matrix = np.linalg.inv(coeff_matrix)
solution_variables = np.dot(inverse_coeff_matrix, const_matrix)

print("\nSolution to the system of equations (using inverse method):")
print("x =", solution_variables[0])
print("y =", solution_variables[1])
print("z =", solution_variables[2])

# Solve the system of equations using np.linalg.solve (alternative method)
solution_linalg = np.linalg.solve(coeff_matrix, const_matrix)  # More efficient method
print("\nSolution using np.linalg.solve:")
print("x =", solution_linalg[0])
print("y =", solution_linalg[1])
print("z =", solution_linalg[2])


A * A^-1 (should be identity matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

Is AB equal to BA? False

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T? True

Solution to the system of equations (using inverse method):
x = 2.0
y = 1.0
z = -2.0

Solution using np.linalg.solve:
x = 2.0
y = 1.0000000000000002
z = -2.0


# 10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

# 1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [10]:
import time
import numpy as np

# Using Python Lists
python_list_1 = [i for i in range(1000000)]
python_list_2 = [i for i in range(1000000)]

start_time = time.time()
python_list_sum = [python_list_1[i] + python_list_2[i] for i in range(len(python_list_1))]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:", end_time - start_time)

# Using NumPy Arrays
numpy_array_1 = np.array(python_list_1)
numpy_array_2 = np.array(python_list_2)

start_time = time.time()
numpy_array_sum = numpy_array_1 + numpy_array_2
end_time = time.time()
print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time)


Time taken for element-wise addition using Python lists: 0.11920475959777832
Time taken for element-wise addition using NumPy arrays: 0.00894618034362793


# 2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [11]:
import time
import numpy as np

# Using Python Lists
start_time = time.time()
python_list_product = [python_list_1[i] * python_list_2[i] for i in range(len(python_list_1))]
end_time = time.time()
print("Time taken for element-wise multiplication using Python lists:", end_time - start_time)

# Using NumPy Arrays
start_time = time.time()
numpy_array_product = numpy_array_1 * numpy_array_2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time)


Time taken for element-wise multiplication using Python lists: 0.10875940322875977
Time taken for element-wise multiplication using NumPy arrays: 0.010037422180175781


# 3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [12]:
# Using Python Lists
start_time = time.time()
python_list_dot_product = sum(python_list_1[i] * python_list_2[i] for i in range(len(python_list_1)))
end_time = time.time()
print("Time taken for dot product using Python lists:", end_time - start_time)

# Using NumPy Arrays
start_time = time.time()
numpy_array_dot_product = np.dot(numpy_array_1, numpy_array_2)
end_time = time.time()
print("Time taken for dot product using NumPy arrays:", end_time - start_time)

Time taken for dot product using Python lists: 0.3692054748535156
Time taken for dot product using NumPy arrays: 0.0030601024627685547


# 4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [13]:
# Using Python Lists
python_matrix_1 = [[i + j for j in range(1000)] for i in range(1000)]
python_matrix_2 = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
python_matrix_multiplication = [[sum(python_matrix_1[i][k] * python_matrix_2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
print("Time taken for matrix multiplication using Python lists:", end_time - start_time)

# Using NumPy Arrays
numpy_matrix_1 = np.array(python_matrix_1)
numpy_matrix_2 = np.array(python_matrix_2)

start_time = time.time()
numpy_matrix_multiplication = np.dot(numpy_matrix_1, numpy_matrix_2)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time)

Time taken for matrix multiplication using Python lists: 217.901837348938
Time taken for matrix multiplication using NumPy arrays: 2.399984359741211
