<a href="https://colab.research.google.com/github/pradhansumitXD/AI-ML/blob/main/AI%26ML_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4. TO - DO - Task Please complete all the problem listed below.



# 4.1 Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [4]:
import numpy as np
def convert_length(value, from_unit, to_unit):
    """
    Convert length between meters and feet.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit to convert from ('m' or 'ft').
    to_unit (str): The unit to convert to ('m' or 'ft').

    Returns:
    float: The converted value.
    """
    if from_unit == 'm' and to_unit == 'ft':
        return np.multiply(value, 3.28084)  # meters to feet
    elif from_unit == 'ft' and to_unit == 'm':
        return np.divide(value, 3.28084)  # feet to meters
    else:
        raise ValueError("Invalid units for length conversion")

def convert_weight(value, from_unit, to_unit):
    """
    Convert weight between kilograms and pounds.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit to convert from ('kg' or 'lbs').
    to_unit (str): The unit to convert to ('kg' or 'lbs').

    Returns:
    float: The converted value.
    """
    if from_unit == 'kg' and to_unit == 'lbs':
        return np.multiply(value, 2.20462)  # kilograms to pounds
    elif from_unit == 'lbs' and to_unit == 'kg':
        return np.divide(value, 2.20462)  # pounds to kilograms
    else:
        raise ValueError("Invalid units for weight conversion")

def convert_volume(value, from_unit, to_unit):
    """
    Convert volume between liters and gallons.

    Parameters:
    value (float): The value to be converted.
    from_unit (str): The unit to convert from ('L' or 'gal').
    to_unit (str): The unit to convert to ('L' or 'gal').

    Returns:
    float: The converted value.
    """
    if from_unit == 'L' and to_unit == 'gal':
        return np.multiply(value, 0.264172)  # liters to gallons
    elif from_unit == 'gal' and to_unit == 'L':
        return np.divide(value, 0.264172)  # gallons to liters
    else:
        raise ValueError("Invalid units for volume conversion")

def main():
    print("Welcome to the unit conversion program!")

    # Choose conversion type
    conversion_type = input("Choose conversion type (length, weight, volume): ").strip().lower()

    if conversion_type not in ['length', 'weight', 'volume']:
        print("Error: Invalid conversion type selected!")
        return

    try:
        # Get value to be converted
        value = float(input("Enter the value to be converted: "))

        # Process based on conversion type
        if conversion_type == 'length':
            from_unit = input("Enter the unit to convert from (m for meters, ft for feet): ").strip()
            to_unit = input("Enter the unit to convert to (m for meters, ft for feet): ").strip()
            result = convert_length(value, from_unit, to_unit)

        elif conversion_type == 'weight':
            from_unit = input("Enter the unit to convert from (kg for kilograms, lbs for pounds): ").strip()
            to_unit = input("Enter the unit to convert to (kg for kilograms, lbs for pounds): ").strip()
            result = convert_weight(value, from_unit, to_unit)

        elif conversion_type == 'volume':
            from_unit = input("Enter the unit to convert from (L for liters, gal for gallons): ").strip()
            to_unit = input("Enter the unit to convert to (L for liters, gal for gallons): ").strip()
            result = convert_volume(value, from_unit, to_unit)

        # Output result
        print(f"The converted value is: {result}")

    except ValueError as e:
        print(f"Error: {e}. Please ensure you enter a valid numeric value and unit combination.")

if __name__ == "__main__":
    main()


Welcome to the unit conversion program!
Choose conversion type (length, weight, volume): volume
Enter the value to be converted: 32
Enter the unit to convert from (L for liters, gal for gallons): 1
Enter the unit to convert to (L for liters, gal for gallons): gal
Error: Invalid units for volume conversion. Please ensure you enter a valid numeric value and unit combination.


# Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).


3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [5]:
def sum_arr(numbers):
    """
    Function to calculate the sum of the numbers in the list.

    Parameters:
    numbers (list): The list of numbers to be summed.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def avg_arr(numbers):
    """
    Function to calculate the average of the numbers in the list.

    Parameters:
    numbers (list): The list of numbers to calculate the average of.

    Returns:
    float: The average of the numbers.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot calculate the average of an empty list")
    return sum(numbers) / len(numbers)

def maximum_arr(numbers):
    """
    Function to find the maximum value in the list.

    Parameters:
    numbers (list): The list of numbers.

    Returns:
    float: The maximum value in the list.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of an empty list")
    return max(numbers)

def minimum_arr(numbers):
    """
    Function to find the minimum value in the list.

    Parameters:
    numbers (list): The list of numbers.

    Returns:
    float: The minimum value in the list.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of an empty list")
    return min(numbers)

def main():
    print("Welcome to the mathematical operations program!")

    try:
        # Get the list of numbers from the user
        numbers = input("Please enter a list of numbers separated by spaces: ").strip().split()

        # Convert the input into a list of floats
        numbers = [float(num) for num in numbers]

        # Ask the user to choose an operation
        operation = input("Choose an operation (sum, average, maximum, minimum): ").strip().lower()

        # Perform the selected operation
        if operation == 'sum':
            result = sum_arr(numbers)
            print(f"The sum of the numbers is: {result}")
        elif operation == 'average':
            result = avg_arr(numbers)
            print(f"The average of the numbers is: {result}")
        elif operation == 'maximum':
            result = maximum_arr(numbers)
            print(f"The maximum value in the list is: {result}")
        elif operation == 'minimum':
            result = minimum_arr(numbers)
            print(f"The minimum value in the list is: {result}")
        else:
            print("Invalid operation selected.")
    except ValueError as e:
        print(f"Error: {e}. Please make sure to enter valid numbers.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Welcome to the mathematical operations program!
Please enter a list of numbers separated by spaces: 5 4 6 8 9 4 1 5 9 
Choose an operation (sum, average, maximum, minimum): sum
The sum of the numbers is: 51.0


# 10. To - Do - NumPy
Please complete all the problems listed below:

# 10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [6]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))

# 2. Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 7)

# 4. Return a new array of zeros with same shape and type as a given array
existing_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(existing_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(existing_array)

# 6. Convert the existing list new_list = [1, 2, 3, 4] to a numpy array
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)

# Output the results
print('empty_array')
print(empty_array)

print("ones_array")
print(ones_array)

print("fill_value_array")
print(fill_value_array)

print("zeros_like_array")
print(zeros_like_array)

print("ones_like_array")
print(ones_like_array)

print("numpy_array_from_list")
print(numpy_array_from_list)


empty_array
[[2.56089693e-316 0.00000000e+000]
 [9.38185117e-154 1.16304933e+214]]
ones_array
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
fill_value_array
[[7 7 7]
 [7 7 7]
 [7 7 7]]
zeros_like_array
[[0 0]
 [0 0]]
ones_like_array
[[1 1]
 [1 1]]
numpy_array_from_list
[1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [7]:
import numpy as np

# 1.an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)

# 2.3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)

# 3.   3x3 identity matrix
arr3 = np.eye(3)

# 4.  random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()

# 5. 10x10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()

# 6. zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element is index 4

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr_to_reverse[::-1]

# 8.  2d array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0

# 9.  8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

# Output the results
print("Array with values from 10 to 49:")
print(arr1)
print("\n3x3 Matrix with values from 0 to 8:")
print(arr2)
print("\n3x3 Identity Matrix:")
print(arr3)
print("\nMean of random array of size 30:")
print(mean_value)
print("\n10x10 Array with random values:")
print(random_10x10)
print("Minimum value :", min_value, "\nMaximum value:", max_value)
print("\nZero array with 5th element replaced by 1:")
print(zero_array)
print("\nReversed array:")
print(reversed_array)
print("\n2D Array with border 1 and inside 0:")
print(border_array)
print("\n8x8 Checkerboard pattern:")
print(checkerboard)


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of random array of size 30:
0.48026636512126775

10x10 Array with random values:
[[0.31771547 0.53981545 0.48718622 0.65334421 0.62068493 0.71287721
  0.52714162 0.7504365  0.28650673 0.67355678]
 [0.15633386 0.60898837 0.15683761 0.00642184 0.603462   0.35063132
  0.51770093 0.65306459 0.89034728 0.4255459 ]
 [0.27326798 0.10629624 0.07149826 0.74210794 0.05808604 0.94760347
  0.6809107  0.89305635 0.02801638 0.58661562]
 [0.73813401 0.09548188 0.27702057 0.7656058  0.96113569 0.10738525
  0.63043906 0.65517006 0.9912896  0.73469271]
 [0.39779844 0.11774518 0.48066986 0.96186591 0.91923807 0.79501013
  0.48738163 0.25272888 0.13617327 0.76632099]
 [0.9766343  0.82707608 0.4194079  0.50155176 0.33861515 0

# Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [8]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
result_add = x + y

# 2. Subtract the two arrays
result_sub = x - y

# 3. Multiply the array with any integers of your choice
result_mul_x = x * 2  # Example: multiplying x by 2
result_mul_y = y * 3  # Example: multiplying y by 3

# 4. Find the square of each element of the array
result_square_x = np.square(x)
result_square_y = np.square(y)

# 5. Find the dot product between: v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

# 6. Concatenate x and y along rows and concatenate v and w along columns
concat_xy_rows = np.concatenate((x, y), axis=0)  # Concatenate along rows
concat_vw_columns = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Concatenate along columns

# 7. Concatenate x and v; if an error occurs, observe and explain why
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempt to concatenate x and v along rows
except Exception as e:
    concat_xv_error = str(e)

# Output the results
print("Addition of x and y:")
print(result_add)
print("\nSubtraction of x and y:")
print(result_sub)
print("\nMultiplying x by 2 and y by 3:")
print(result_mul_x)
print(result_mul_y)
print("\nSquare of elements in x:")
print(result_square_x)
print("\nSquare of elements in y:")
print(result_square_y)
print("\nDot product of v and w:")
print(dot_vw)
print("\nDot product of x and v:")
print(dot_xv)
print("\nDot product of x and y:")
print(dot_xy)
print("\nConcatenate x and y along rows:")
print(concat_xy_rows)
print("\nConcatenate v and w along columns:")
print(concat_vw_columns)
print("\nConcatenating x and v :")
print(concat_xv_error )


Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplying x by 2 and y by 3:
[[ 2  4]
 [ 6 10]]
[[15 18]
 [21 24]]

Square of elements in x:
[[ 1  4]
 [ 9 25]]

Square of elements in y:
[[25 36]
 [49 64]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

Concatenating x and v :
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]])   and    B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [9]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 (should be identity matrix):")
print(identity_matrix)

# 2. Prove AB != BA
AB = np.dot(A, B)  # AB
BA = np.dot(B, A)  # BA
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)
print("\nIs AB equal to BA?", np.array_equal(AB, BA))  # Checking if AB == BA

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)  # (AB)^T
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))  # B^T * A^T
print("\n(AB)^T:")
print(AB_T)
print("\nB^T * A^T:")
print(B_T_A_T)
print("\nIs (AB)^T equal to B^T * A^T? is " , np.array_equal(AB_T, B_T_A_T))

# Solve the system of linear equations using inverse method:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system in matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Use the inverse of A_eq to solve for X (where X = [x, y, z])
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)

print("\nSolution to the system of equations (using inverse method):")
print("x = ", X[0])
print("y = ", X[1])
print("z = ", X[2])

# Solve the system of equations using np.linalg.solve (alternative method)
X_linalg = np.linalg.solve(A_eq, B_eq)  # This is a more efficient way to solve the system
print("\nSolution using np.linalg.solve:")
print("x = ", X_linalg[0])
print("y = ", X_linalg[1])
print("z = ", X_linalg[2])


A * A^-1 (should be identity matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

Is AB equal to BA? False

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T? is  True

Solution to the system of equations (using inverse method):
x =  2.0
y =  1.0
z =  -2.0

Solution using np.linalg.solve:
x =  2.0
y =  1.0000000000000002
z =  -2.0


# 10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

# 1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [10]:
import time
import numpy as np

# Using Python Lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:", end_time - start_time)

# Using NumPy Arrays
np_array1 = np.array(list1)
np_array2 = np.array(list2)

start_time = time.time()
np_addition = np_array1 + np_array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time)


Time taken for element-wise addition using Python lists: 0.052770376205444336
Time taken for element-wise addition using NumPy arrays: 0.0033071041107177734


# 2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [11]:
# Using Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print("Time taken for element-wise multiplication using Python lists:", end_time - start_time)

# Using NumPy Arrays
start_time = time.time()
np_multiplication = np_array1 * np_array2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time)


Time taken for element-wise multiplication using Python lists: 0.10521173477172852
Time taken for element-wise multiplication using NumPy arrays: 0.004758119583129883


# 3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [12]:
# Using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print("Time taken for dot product using Python lists:", end_time - start_time)

# Using NumPy Arrays
start_time = time.time()
dot_product_np = np.dot(np_array1, np_array2)
end_time = time.time()
print("Time taken for dot product using NumPy arrays:", end_time - start_time)

Time taken for dot product using Python lists: 0.06627011299133301
Time taken for dot product using NumPy arrays: 0.001941680908203125


# 4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [13]:
# Using Python Lists
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
matrix_multiplication_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
print("Time taken for matrix multiplication using Python lists:", end_time - start_time)

# Using NumPy Arrays
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

start_time = time.time()
matrix_multiplication_np = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time)


Time taken for matrix multiplication using Python lists: 189.83953547477722
Time taken for matrix multiplication using NumPy arrays: 0.9243419170379639
